---
k8s_version: "1.34.1"
kubernetes_public_address: "10.0.0.10"
etcd_servers: "{%- for host in groups['controllers'] -%}https://{{ hostvars[host]['ansible_host'] }}:2379{%- if not loop.last -%},{%- endif -%}{%- endfor -%}"
