---
- name: Install and configure etcd
  hosts: controllers
  become: yes
  vars:
    etcd_version: "3.5.12"
    etcd_initial_cluster: "{%- for host in groups['controllers'] -%} {{ host }}=https://{{ hostvars[host]['ansible_host'] }}:2380{%- if not loop.last -%},{%- endif %}{% endfor -%}"

  tasks:
    - name: Download etcd binary
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
        dest: "/tmp/etcd.tar.gz"
        mode: "0755"

    - name: Extract etcd binary
      unarchive:
        src: "/tmp/etcd.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move etcd binary to /usr/local/bin
      copy:
        src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
        remote_src: yes
      loop: [etcd, etcdctl]

    - name: Create etcd data directory
      file:
        path: /var/lib/etcd
        state: directory
        mode: "0700"

    - name: Create systemd unit file template
      template:
        src: ../templates/etcd.service.j2
        dest: /etc/systemd/system/etcd.service
        mode: "0644"
      notify:
        - restart etcd

    - name: Start etcd service
      systemd:
        name: etcd
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: restart etcd
      systemd:
        name: etcd
        state: restarted
