---
- name: Prepare nodes for Kubernetes The Hard Way
  hosts: k8s
  become: true
  tasks:
    - name: Display SWAP
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set sysctl parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop:
        - name: net.bridge.bridge-nf-call-iptables
          value: 1
        - name: net.bridge.bridge-nf-call-ip6tables
          value: 1
        - name: net.ipv4.ip_forward
          value: 1

    - name: Install base dependencies
      apt:
        name:
          [
            apt-transport-https,
            ca-certificates,
            curl,
            gnupg,
            lsb-release,
            gpg,
            socat,
            conntrack,
            ipset,
          ]
        state: present
        update_cache: yes

    - name: Ensure /etc/kubernetes/pki exists
      file:
        path: /etc/kubernetes/pki
        state: directory
        mode: "0755"
